<a href="https://colab.research.google.com/github/SobiaNoorAI/Python/blob/main/Pandas%20/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Install Pandas**

To install Pandas, open cmd on your PC or laptop. Write the pip install command in the cmd.

In [ ]:
pip install pandas

**CMD**

![panda install.PNG]()

**Import pandas Library**

In [1]:
#import pandas library
import pandas as pd

# Creating Data

**Create a Series**

In [ ]:
# create a list
student_list =['Harry', 'Hermione', 'Ron']

#convert student list into a Series
student_series = pd.Series(student_list)
student_series

0       Harry
1    Hermione
2         Ron
dtype: object

In [ ]:
#access the Harry throgh index
print(student_series[0])

Harry

**Create a DataFrame**

In [ ]:
#create DataFrame in Key:Value form
student_attendance = pd.DataFrame({"Harry":[1,0,1,1,0], "Hermione":[1,1,1,1,1], "Ron":[1,0,0,0,0]})
student_attendance

   Harry  Hermione  Ron
0      1         1    1
1      0         1    0
2      1         1    0
3      1         1    0
4      0         1    0

 **Change Label's Index**

In [ ]:
student_attendance = pd.DataFrame({"Harry":[1,0,1,1,0], "Hermione":[1,1,1,1,1], "Ron":[1,0,0,0,0]}
,index=['Monday',' Tuesday',' Wednesday', 'Thursday',' Friday'])
student_attendance

            Harry  Hermione  Ron
Monday          1         1    1
 Tuesday        0         1    0
 Wednesday      1         1    0
Thursday        1         1    0
 Friday         0         1    0

**Accessing Elements**

In [ ]:
#access Monday Label
student_attendance.loc['Monday']

Harry       1
Hermione    1
Ron         1
Name: Monday, dtype: int64

**Accessing Slices**

In [ ]:
#access slice from Monday to Thursday
student_attendance['Monday':'Thursday']

            Harry  Hermione  Ron
Monday          1         1    1
 Tuesday        0         1    0
 Wednesday      1         1    0
Thursday        1         1    0

**Access all Columns**

In [ ]:
#access two columns
student_attendance.columns

Index(['Harry', 'Hermione', 'Ron'], dtype='object')

**Access Specific Column's data**

In [ ]:
student_attendance[['Harry', 'Ron']]

            Harry  Ron
Monday          1    1
 Tuesday        0    0
 Wednesday      1    0
Thursday        1    0
 Friday         0    0

# Reading Data in Pandas

**Open Excel File**

In [ ]:
import pandas as pd

xlsx_url = r'https://raw.githubusercontent.com/SobiaNoorAI/Python/main/Pandas%20/student_result.xlsx'

#open excel file
student_result = pd.read_excel(xlsx_url, sheet_name='Sheet1')
student_result

    StudentID      Name  Age  Grade  Score
0           1     Harry   11      4   65.0
1           2  Hermione   11      4   95.0
2           3       Ron   11      4   45.0
3           4     Ginny   10      3   80.0
4           5     Draco   11      4   75.0
5           6       Cho   12      5    NaN
6           7   Neville   13      6    NaN
7           8      Luna   15      8    NaN
8           9    Cedric   17     10    NaN
9          10    George   16      9   60.0
10         11      Fred   16      9   50.0
11         12    Seamus   14      7   40.0
12         13    Padma    13      6   86.0
13         14     Nigel   17     10   35.0
14         14     Nigel   17     10   35.0

**Open CSV File**

In [7]:
#\student_data.csv
import pandas as pd

csv_url = r'https://raw.githubusercontent.com/SobiaNoorAI/Python/main/Pandas%20/student_data.csv'

#open excel file
student_data = pd.read_csv(csv_url)
student_data

    Student_ID      Name Admission_Date
0            1     Harry       9/1/1991
1            2  Hermione       9/2/1991
2            3       Ron       9/3/1991
3            4     Ginny       9/4/1992
4            5     Draco       9/5/1991
5            6       Cho       9/6/1990
6            7   Neville       9/7/1989
7            8      Luna       9/8/1987
8            9    Cedric       9/9/1985
9           10    George      9/10/1986
10          11      Fred      9/11/1986
11          12    Seamus            NaN
12          13     Padma      9/13/1989
13          14     Nigel      9/14/1985
14          14     Nigel      9/15/1985
15          15     James             \t

**head():** display top rows

In [ ]:
# display top ten rows
student_result.head(10)

   StudentID      Name  Age  Grade  Score
0          1     Harry   11      4   65.0
1          2  Hermione   11      4   95.0
2          3       Ron   11      4   45.0
3          4     Ginny   10      3   80.0
4          5     Draco   11      4   75.0
5          6       Cho   12      5    NaN
6          7   Neville   13      6    NaN
7          8      Luna   15      8    NaN
8          9    Cedric   17     10    NaN
9         10    George   16      9   60.0

**tail():** display bottom rows

In [ ]:
# display last 10 rows
student_result.tail(10)

    StudentID     Name  Age  Grade  Score
5           6      Cho   12      5    NaN
6           7  Neville   13      6    NaN
7           8     Luna   15      8    NaN
8           9   Cedric   17     10    NaN
9          10   George   16      9   60.0
10         11     Fred   16      9   50.0
11         12   Seamus   14      7   40.0
12         13   Padma    13      6   86.0
13         14    Nigel   17     10   35.0
14         14    Nigel   17     10   35.0

**info():** display number of rows, columns, datatypes, and memory usage

In [ ]:
#info student_result
student_result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  15 non-null     int64
 1   Name       15 non-null     object
 2   Age        15 non-null     int64
 3   Grade      15 non-null     int64
 4   Score      11 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 728.0+ bytes

**describe():** display min, max, and mean values etc.

In [ ]:
student_result.describe()

       StudentID        Age      Grade      Score
count  15.000000  15.000000  15.000000  11.000000
mean    7.933333  13.600000   6.600000  60.545455
std     4.366539   2.557901   2.557901  21.266705
min     1.000000  10.000000   3.000000  35.000000
25%     4.500000  11.000000   4.000000  42.500000
50%     8.000000  13.000000   6.000000  60.000000
75%    11.500000  16.000000   9.000000  77.500000
max    14.000000  17.000000  10.000000  95.000000

**value_counts():** count occurance of a value

In [ ]:
#description of column Score
#Use value_counts directly on the column
student_result['Score'].value_counts()

Score
35.0    2
65.0    1
95.0    1
45.0    1
80.0    1
75.0    1
60.0    1
50.0    1
40.0    1
86.0    1
Name: count, dtype: int64

**mean():** display mean value of column

In [ ]:
#Mean value of column
student_result['Score'].mean()

60.54545454545455

**min():** display max value of column

In [ ]:
#min value of column
student_result['Score'].min()

35.0

**max():** display max value of column

In [ ]:
#max value of column
student_result['Score'].max()

95.0

# Cleaning Data

In data analysis, cleaning of bad data is important as it can affect the results. Sometimes, we get empty cells, duplicate values, and wrong data types in the data.

**isnull():** check null values

In [ ]:
#represent null values with True
student_result.isnull()

    StudentID   Name    Age  Grade  Score
0       False  False  False  False  False
1       False  False  False  False  False
2       False  False  False  False  False
3       False  False  False  False  False
4       False  False  False  False  False
5       False  False  False  False   True
6       False  False  False  False   True
7       False  False  False  False   True
8       False  False  False  False   True
9       False  False  False  False  False
10      False  False  False  False  False
11      False  False  False  False  False
12      False  False  False  False  False
13      False  False  False  False  False
14      False  False  False  False  False

**Total Null Values**

In [ ]:
#represent null values with True
student_result.isnull().sum()

StudentID    0
Name         0
Age          0
Grade        0
Score        4
dtype: int64

In [ ]:
student_data.isnull()

    Student_ID   Name  Admission_Date
0        False  False           False
1        False  False           False
2        False  False           False
3        False  False           False
4        False  False           False
5        False  False           False
6        False  False           False
7        False  False           False
8        False  False           False
9        False  False           False
10       False  False           False
11       False  False            True
12       False  False           False
13       False  False           False
14       False  False           False
15       False  False           False

**dropna():** drop null values

In [ ]:
#drop null data
student_data_dropped = student_data.dropna()
print("\n Drop the row of Student Seamus, ID = 12, It's data is missing:")
student_data_dropped

 Drop the row of Student Seamus, ID = 12, It's data is missing:

    Student_ID      Name Admission_Date
0            1     Harry       9/1/1991
1            2  Hermione       9/2/1991
2            3       Ron       9/3/1991
3            4     Ginny       9/4/1992
4            5     Draco       9/5/1991
5            6       Cho       9/6/1990
6            7   Neville       9/7/1989
7            8      Luna       9/8/1987
8            9    Cedric       9/9/1985
9           10    George      9/10/1986
10          11      Fred      9/11/1986
12          13     Padma      9/13/1989
13          14     Nigel      9/14/1985
14          14     Nigel      9/15/1985
15          15     James             \t

**Fill Missing Data**

**fillna()**

This is the second way to deal with bad data. We used fillna() function to replace null values with new values. This function is productive where we are not allowed to drop data.

In [ ]:
#replace null value with 40
fill_with_value=student_result['Score'].fillna(40)
student_result['Score']=fill_with_value
student_result

    StudentID      Name  Age  Grade  Score
0           1     Harry   11      4   65.0
1           2  Hermione   11      4   95.0
2           3       Ron   11      4   45.0
3           4     Ginny   10      3   80.0
4           5     Draco   11      4   75.0
5           6       Cho   12      5   40.0
6           7   Neville   13      6   40.0
7           8      Luna   15      8   40.0
8           9    Cedric   17     10   40.0
9          10    George   16      9   60.0
10         11      Fred   16      9   50.0
11         12    Seamus   14      7   40.0
12         13    Padma    13      6   86.0
13         14     Nigel   17     10   35.0
14         14     Nigel   17     10   35.0

In [2]:
import pandas as pd

xlsx_url = r'https://raw.githubusercontent.com/SobiaNoorAI/Python/main/Pandas%20/student_result.xlsx'

#open excel file
student_result = pd.read_excel(xlsx_url, sheet_name='Sheet1')
student_result

    StudentID      Name  Age  Grade  Score
0           1     Harry   11      4   65.0
1           2  Hermione   11      4   95.0
2           3       Ron   11      4   45.0
3           4     Ginny   10      3   80.0
4           5     Draco   11      4   75.0
5           6       Cho   12      5    NaN
6           7   Neville   13      6    NaN
7           8      Luna   15      8    NaN
8           9    Cedric   17     10    NaN
9          10    George   16      9   60.0
10         11      Fred   16      9   50.0
11         12    Seamus   14      7   40.0
12         13    Padma    13      6   86.0
13         14     Nigel   17     10   35.0
14         14     Nigel   17     10   35.0

**Replace Missing Values with mean()**

In [4]:
#Replace using mean value
score_mean= student_result['Score'].mean()
fill_with_mean = student_result['Score'].fillna(score_mean, inplace=True)

print("\n Replace Missing Scores with mean value :")
student_result

 Replace Missing Scores with mean value :

<ipython-input-4-a2c0a77d9bca>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fill_with_mean = student_result['Score'].fillna(score_mean, inplace=True)

    StudentID      Name  Age  Grade      Score
0           1     Harry   11      4  65.000000
1           2  Hermione   11      4  95.000000
2           3       Ron   11      4  45.000000
3           4     Ginny   10      3  80.000000
4           5     Draco   11      4  75.000000
5           6       Cho   12      5  60.545455
6           7   Neville   13      6  60.545455
7           8      Luna   15      8  60.545455
8           9    Cedric   17     10  60.545455
9          10    George   16      9  60.000000
10         11      Fred   16      9  50.000000
11         12    Seamus   14      7  40.000000
12         13    Padma    13      6  86.000000
13         14     Nigel   17     10  35.000000
14         14     Nigel   17     10  35.000000

**Remove Duplicates**

Firstly, the duplicated() function finds the duplicate values. Then, the drop_duplicates() function removes duplicate data. The duplicate values are represented by True.

In [ ]:
student_result.duplicated()
student_result

    StudentID      Name  Age  Grade      Score
0           1     Harry   11      4  65.000000
1           2  Hermione   11      4  95.000000
2           3       Ron   11      4  45.000000
3           4     Ginny   10      3  80.000000
4           5     Draco   11      4  75.000000
5           6       Cho   12      5  60.545455
6           7   Neville   13      6  60.545455
7           8      Luna   15      8  60.545455
8           9    Cedric   17     10  60.545455
9          10    George   16      9  60.000000
10         11      Fred   16      9  50.000000
11         12    Seamus   14      7  40.000000
12         13    Padma    13      6  86.000000
13         14     Nigel   17     10  35.000000
14         14     Nigel   17     10  35.000000

`StudentID` 14, Nigel has duplicate data.

**drop_duplicates():** drop duplicate values

In [ ]:
import pandas as pd

xlsx_url = r'https://raw.githubusercontent.com/SobiaNoorAI/Python/main/Pandas%20/student_result.xlsx'

#open excel file
student_result = pd.read_excel(xlsx_url, sheet_name='Sheet1')

#drop duplicate data
student_result.drop_duplicates(inplace = True)
print("\n Drop the duplicate data:")
student_result

 Drop the duplicate data:

    StudentID      Name  Age  Grade  Score
0           1     Harry   11      4   65.0
1           2  Hermione   11      4   95.0
2           3       Ron   11      4   45.0
3           4     Ginny   10      3   80.0
4           5     Draco   11      4   75.0
5           6       Cho   12      5    NaN
6           7   Neville   13      6    NaN
7           8      Luna   15      8    NaN
8           9    Cedric   17     10    NaN
9          10    George   16      9   60.0
10         11      Fred   16      9   50.0
11         12    Seamus   14      7   40.0
12         13    Padma    13      6   86.0
13         14     Nigel   17     10   35.0

Now, duplicate data of Nigel has been removed.

**Conditional Selection**

In [ ]:
#select rows where age is above 15
older_students = student_result[student_result['Age'] > 15]
older_students

    StudentID    Name  Age  Grade  Score
8           9  Cedric   17     10    NaN
9          10  George   16      9   60.0
10         11    Fred   16      9   50.0
13         14   Nigel   17     10   35.0

Create New Column From the Existing Column

Here, create new column `Pass` from Conditional selection of Column `Score`

In [ ]:
#select data from Score column
student_result['Pass'] = student_result['Score'] >= 50

#save data in new column
student_result[student_result['Pass'] == True]

    StudentID      Name  Age  Grade  Score  Pass
0           1     Harry   11      4   65.0  True
1           2  Hermione   11      4   95.0  True
3           4     Ginny   10      3   80.0  True
4           5     Draco   11      4   75.0  True
9          10    George   16      9   60.0  True
10         11      Fred   16      9   50.0  True
12         13    Padma    13      6   86.0  True

**Rename Column**

In [ ]:
#change column name from Pass to Remark
student_result.rename(columns={'Pass':'Remark'}, inplace=True)
student_result

    StudentID      Name  Age  Grade  Score  Remark
0           1     Harry   11      4   65.0    True
1           2  Hermione   11      4   95.0    True
2           3       Ron   11      4   45.0   False
3           4     Ginny   10      3   80.0    True
4           5     Draco   11      4   75.0    True
5           6       Cho   12      5    NaN   False
6           7   Neville   13      6    NaN   False
7           8      Luna   15      8    NaN   False
8           9    Cedric   17     10    NaN   False
9          10    George   16      9   60.0    True
10         11      Fred   16      9   50.0    True
11         12    Seamus   14      7   40.0   False
12         13    Padma    13      6   86.0    True
13         14     Nigel   17     10   35.0   False

# Grouping and Sorting Data

**Groupby():** Divide our data into groups according to specific columns

In [5]:
# group data based on Grade column
grade_avg_scores = student_result.groupby('Grade')['Score'].median()

print("\nAverage Score by Grade:")
grade_avg_scores

Average Score by Grade:

Grade
3     80.000000
4     70.000000
5     60.545455
6     73.272727
7     40.000000
8     60.545455
9     55.000000
10    35.000000
Name: Score, dtype: float64

Here, we make a group of the data according to grade and then find the median value.

**Joining Data**

To join data, we use the merge() function.

In [ ]:
#merge two tables through Common Column like ID
merged_data = pd.merge(DataFrame1, DataFrame2, on="ID",how="inner")

print("Merged Data:")
print(merged_data)

In [11]:
#merge two tables through Student_ID
#merged_data = pd.merge(student_result, student_data, on="Student_ID",how="inner")
merged_data = pd.merge(student_result, student_data, left_on='StudentID', right_on='Student_ID')

print("Merged Data:")
print(merged_data)

Merged Data:
    StudentID    Name_x  Age  Grade      Score  Student_ID    Name_y  \
0           1     Harry   11      4  65.000000           1     Harry
1           2  Hermione   11      4  95.000000           2  Hermione
2           3       Ron   11      4  45.000000           3       Ron
3           4     Ginny   10      3  80.000000           4     Ginny
4           5     Draco   11      4  75.000000           5     Draco
5           6       Cho   12      5  60.545455           6       Cho
6           7   Neville   13      6  60.545455           7   Neville
7           8      Luna   15      8  60.545455           8      Luna
8           9    Cedric   17     10  60.545455           9    Cedric
9          10    George   16      9  60.000000          10    George
10         11      Fred   16      9  50.000000          11      Fred
11         12    Seamus   14      7  40.000000          12    Seamus
12         13    Padma    13      6  86.000000          13     Padma
13         14     Nigel   17     10  35.000000          14     Nigel
14         14     Nigel   17     10  35.000000          14     Nigel
15         14     Nigel   17     10  35.000000          14     Nigel
16         14     Nigel   17     10  35.000000          14     Nigel

   Admission_Date
0        9/1/1991
1        9/2/1991
2        9/3/1991
3        9/4/1992
4        9/5/1991
5        9/6/1990
6        9/7/1989
7        9/8/1987
8        9/9/1985
9       9/10/1986
10      9/11/1986
11            NaN
12      9/13/1989
13      9/14/1985
14      9/15/1985
15      9/14/1985
16      9/15/1985

**sort_values():** sorts the data based on some column.

It sorts the data in ascending mode by default.

In [12]:
#sort merge data in ascending order of Score
sorted_by_score = student_result.sort_values(by="Score", ascending=False)
print("Sorted by  Score:")
print(sorted_by_score)

Sorted by  Score:
    StudentID      Name  Age  Grade      Score
1           2  Hermione   11      4  95.000000
12         13    Padma    13      6  86.000000
3           4     Ginny   10      3  80.000000
4           5     Draco   11      4  75.000000
0           1     Harry   11      4  65.000000
5           6       Cho   12      5  60.545455
6           7   Neville   13      6  60.545455
7           8      Luna   15      8  60.545455
8           9    Cedric   17     10  60.545455
9          10    George   16      9  60.000000
10         11      Fred   16      9  50.000000
2           3       Ron   11      4  45.000000
11         12    Seamus   14      7  40.000000
13         14     Nigel   17     10  35.000000
14         14     Nigel   17     10  35.000000